app:
  name: 'avito_intern'
  version: '1.0.0'

http:
  port: '8000'

logger:
  log_level: 'debug'
  rollbar_env: 'docker_avito'
jwt:
  secret_key: "slatt"
postgres:
  username: "docker_avito"
  password: "docker_avito"
  host: "db"
  port: "5432"
  name: "docker_avito"
  pool_max: 10
redis:
  address: "localhost:6379"
  password: ""
  db: 0